FROM httpd:2.4
copy ./nanomine-httpd.conf /usr/local/apache2/conf/httpd.conf
copy nanomine_oit_duke_edu.key /usr/local/apache2/conf/server.key
copy nanomine_oit_duke_edu_cert.cer /usr/local/apache2/conf/server.crt



