#!/bin/bash
# run the python server on localhost or a non-exposed other host
# Adjust the apache proxy to point to the correct host/port
source ~nanomine/nanomine_prod_env
source ~nanomine/nanomine/venv/bin/activate
cd ~nanomine/nanomine
kill $(ps -eo pid,args | grep 'python manage.py runserver'|grep -v grep | awk '{print $1}')
python manage.py migrate
nohup python manage.py runserver localhost:8000 --noreload &
