#!/bin/bash
# run the python server on localhost or a non-exposed other host
# Adjust the apache proxy to point to the correct host/port
source ~nanomine/nanomine_prod_env
source ~nanomine/nanomine/bin/activate
cd ~nanomine/nanomine
python manage.py migrate
nohup python manage.py runserver localhost:8000 --noreload &
