#!/bin/bash
source ~nanomine/nanomine_prod_env
docker stop apache
docker rm apache
export INT_DOCS=/usr/local/apache2/nanodocs
export EXT_DOCS=${NM_WEB_STATIC}
docker run --network="host" -dit -v${EXT_DOCS}:${INT_DOCS} --name apache apachedev

