#!/bin/bash
mongo --port $NM_PROD_MONGO_PORT -u $NM_MONGO_USER -p $NM_MONGO_PWD --authenticationDatabase admin <<EOF
use mgi
db.createUser({
  user: "${NM_PROD_USER}",
  pwd: "${NM_PROD_PWD}",
  roles: ["readWrite"]
});
EOF

